packaging_format = 2

id = "redirect"
name = "Redirect"
description.en = "Create a redirection or a proxy to another path"
description.fr = "Créer une redirection ou un proxy vers un autre emplacement"

version = "1.0.2~ynh1"

maintainers = ["alexAubin"]

[upstream]
license = "AGPL-3.0-or-later"
code = "https://github.com/YunoHost-Apps/redirect_ynh"
website = "https://github.com/YunoHost-Apps/redirect_ynh"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.2.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/redirect"

    [install.redirect_path]
    ask.en = "Redirect destination path"
    ask.fr = "Emplacement de destination"
    type = "string"
    example = "http://127.0.0.1:8080/app/"
    default = "http://127.0.0.1"

    [install.redirect_type]
    ask.en = "Redirect type"
    ask.fr = "Type de redirection"
    type = "string"
    default = "public_302"

    [install.redirect_type.choices]
public_302 = "Visible redirect (302, temporary). Everybody will be able to access it."
public_301 = "Visible redirect (301, permanent). Everybody will be able to access it."
public_proxy = "Proxy, invisible (NGINX proxy_pass). Everybody will be able to access it."
private_proxy = "Proxy, invisible (NGINX proxy_pass). Only accessible for allowed users."

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
