#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# Copia de seguridad de la configuración de Nginx
#=================================================

ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf"

#=================================================
# FIN DEL SCRIPT
#=================================================

ynh_print_info "Script de copia de seguridad completado para $app. (Yunohost entonces copiará esos archivos al archivo)."
