#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# Modificar URL en nginx conf
#=================================================
ynh_script_progression "Actualización de la configuración del servidor web NGINX..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_change_url_nginx

#=================================================
# Fin del SCRIPT
#=================================================

ynh_script_progression "Cambio de URL completado para $app"
