#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

_validate_redirect_uri

#=================================================
# CONFIGURANDO NGINX
#=================================================
ynh_script_progression "Configuración del servidor web Nginx..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_add_nginx

#=================================================
# FIN DEL SCRIPT
#=================================================

ynh_script_progression "Instalación de $app completa"
