#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ELIMINANDO LA CONFIGURACION DE Nginx
#=================================================

ynh_config_remove_nginx

#=================================================
# FIN DEL SCRIPT
#=================================================

ynh_script_progression "Eliminación de $app completa"
