#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_restore "/etc/nginx/conf.d/${domain}.d/${app}.conf"

ynh_script_progression "Recarga el servidor web Nginx..."
ynh_systemctl --service=nginx --action=reload

#=================================================
# FIN DEL SCRIPT
#=================================================

ynh_script_progression "Restauración completada para $app"
