#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ASEGURAR LA COMPATIBILIDAD DESCENDENTE
#=================================================

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
else
    redirect_type="redirect"
fi
ynh_app_setting_set --key='redirect_type' --value=$redirect_type

if [[ -z "${target:-}" ]] && [[ -n "${redirect_path:-}" ]]; then
    target="$redirect_path"
    ynh_app_setting_delete --key=redirect_path
    ynh_app_setting_set --key=target --value="$target"
fi

#=================================================
# CONFIGURACION NGINX
#=================================================
ynh_script_progression "Configuración del servidor web Nginx..."

mv ../conf/{nginx-$redirect_type.conf,nginx.conf}
ynh_config_add_nginx

ynh_script_progression "Actualización de $app completa"
